name: simple test
on: [push]

env:
  RUST_BACKTRACE: 1

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: build rs
        run: |
          rustc main.rs

      - name: run
        run: |
            ./main

      - name: build cu
        run: |
          nvcc main.cu

      - name: run
        run: |
            ./a.out

